<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472;net8.0</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FodyHelpers" />
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Microsoft.CSharp" />
    <ProjectReference Include="..\AssemblyToProcessExplicit\AssemblyToProcessExplicit.csproj" />
    <ProjectReference Include="..\NullGuard.Fody\NullGuard.Fody.csproj" />
  </ItemGroup>
</Project>